'use client';
import {useEffect,useRef,useState} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'framer-motion';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import {ArrowUpRight,ArrowRight,ShoppingBag,Check,Plus,Minus,Zap,Heart,Layers,Headphones,Menu,X,Trash2,Mail,Camera as Instagram} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import './forma.css';
import './interactions.css';
export function Workspace({small=false,title='Your life, beautifully together.'}:{small?:boolean,title?:string}){return <div className={`workspace ${small?'small':''}`}><div className="windowbar"><span>◧ &nbsp; forma / life planner</span><span>•••</span></div><div className="cover"><span>MAKE ROOM FOR WHAT MATTERS</span></div><div className="workspace-body"><span className="ws-icon">✳</span><h3>{title}</h3><p>A little intention goes a long way. Welcome to your space.</p><div className="ws-tabs">⌂ &nbsp; My dashboard <span>↗ &nbsp; Quick links</span></div><div className="ws-grid"><div><b>Today, with intention</b>{['A slow start & a good coffee','Move one idea forward','Make something just for you'].map(t=><div className="ws-task" key={t}><i/> {t}</div>)}<div className="ws-note">One thing at a time.<br/><em>You’re doing enough.</em></div></div><div><b>Your little corner</b><div className="ws-photo"/><div className="ws-links">↗ Weekly reset<br/>↗ Goals & dreams<br/>↗ The good stuff</div></div></div></div></div>}
const products=[
{id:1,slug:'life-planner',title:'The Life Planner',category:'Life & wellness',price:500,color:'sage',badge:'Bestseller',description:'A calmer home for your goals, habits, and everything in between.',features:['Daily & weekly planning','Habit and mood trackers','Goals, journal & life dashboard']},
{id:2,slug:'creator-studio',title:'The Creator Studio',category:'Work & business',price:500,color:'peach',badge:'Creator favorite',description:'Big ideas deserve a beautiful place to become real.',features:['Content calendar & idea bank','Brand and campaign planning','Client projects & deliverables']},
{id:3,slug:'second-brain',title:'The Second Brain',category:'Productivity',price:500,color:'lavender',badge:'New',description:'Less mental clutter. More space for your next good idea.',features:['Knowledge and resource library','Projects, areas & archive','Quick capture inbox']},
{id:4,slug:'study-space',title:'The Study Space',category:'Student life',price:500,color:'blue',badge:'Fresh pick',description:'Your semester, sorted. A little less stress, a lot more clarity.',features:['Course & assignment tracker','Study schedule & notes','Exam countdown dashboard']},
{id:5,slug:'gentle-reset',title:'The Gentle Reset',category:'Life & wellness',price:500,color:'peach',badge:'Start here',description:'Small rituals that make your everyday feel a little more like you.',features:['Weekly reset ritual','Gratitude journal','Mindful routine builder']},
{id:6,slug:'freelance-hq',title:'The Freelance HQ',category:'Work & business',price:500,color:'sage',badge:'All in one',description:'A home for the business you’re building on your own terms.',features:['Client CRM & project hub','Invoice and income tracker','Proposals & meeting notes']}];
type Product=typeof products[number];
const bundle:Product={id:99,slug:'everything-bundle',title:'The Everything Bundle',category:'Bundle',price:500,color:'lavender',badge:'Bundle Deal',description:'All six templates. One beautifully connected life.',features:['All 6 Forma templates','Lifetime template updates','30 days of setup support']};
const categories=['All templates','Life & wellness','Work & business','Productivity','Student life'];
const questions=[
['Do I need to know how to use Notion?','Not at all. Every template is designed to feel intuitive, with a quick-start guide and example content. If you can tick a box and type a note, you’re ready.'],
['Does this work with the free Notion plan?','Yes. All six templates are designed to work with Notion’s free personal plan. No extra subscription is required to use the included dashboards and databases.'],
['How do I receive my templates?','Once connected to a live checkout, purchases will provide a Notion duplication link. Open it, choose Duplicate, and make the template yours. This demo does not process payments or deliver paid products.'],
['Can I make it my own?','Absolutely. Change colors, rearrange pages, add your own sections, or remove what you don’t need. Think of Forma as your starting point, not a rulebook.'],
['What if I need a little help?','The proposed offer includes a getting-started guide and 30 days of setup support. Before launching, add your real support address and publish your refund and support policies.']];
const quotes=[
['“Finally, a planner that feels like me. Everything has a home, and my brain can take a breath.”','Jamie R.','Designer & beautifully busy human','JR'],
['“I went from seventeen scattered docs to one space I actually want to open every morning.”','Alex M.','Independent creator','AM'],
['“The perfect balance of pretty and practical. My Sunday reset is now my favorite ritual.”','Sofia L.','Student & side-project enthusiast','SL']];
function Magnetic({children,href,onClick,className=''}:{children:React.ReactNode,href?:string,onClick?:()=>void,className?:string}){
const move=(e:React.MouseEvent<HTMLElement>)=>{if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.12}px,${(e.clientY-r.top-r.height/2)*.18}px)`;}};
const reset=(e:React.MouseEvent<HTMLElement>)=>{e.currentTarget.style.transform='translate(0,0)'};
return href?<a href={href} className={'button '+className} data-cursor="Explore" onMouseMove={move} onMouseLeave={reset}>{children}</a>:<button className={'button '+className} data-cursor="Buy" onClick={onClick} onMouseMove={move} onMouseLeave={reset}>{children}</button>;
}
function Counter({value,label}:{value:number,label:string}){const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{if(!ref.current)return;const el=ref.current;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){if(!matchMedia('(prefers-reduced-motion:reduce)').matches){const n={v:0};gsap.to(n,{v:value,duration:1.7,ease:'power2.out',onUpdate:()=>{el.textContent=Math.round(n.v).toLocaleString('en-US')+'+';}});}observer.disconnect();}},{threshold:.6});observer.observe(el);return()=>observer.disconnect()},[value]);return <div><span className="stat-number" ref={ref}>{value.toLocaleString('en-US')}+</span><span className="stat-label">{label}</span></div>}
function ProductCard({product,onView,formatPrice,onTrack}:{product:Product,onView:(p:Product)=>void,formatPrice:(amount:number)=>string,onTrack:(p:Product)=>void}){return <motion.button layout className={'product-card '+product.color} data-cursor="View" onClick={()=>{onTrack(product);onView(product)}} onMouseMove={e=>{if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`perspective(900px) rotateX(${-(e.clientY-r.top-r.height/2)/70}deg) rotateY(${(e.clientX-r.left-r.width/2)/70}deg)`}}} onMouseLeave={e=>{e.currentTarget.style.transform='perspective(900px) rotateX(0deg) rotateY(0deg)'}}><div className="product-visual"><span className="product-badge">{product.badge}</span><div className="product-screen"><Workspace small title={product.title}/></div><div className="card-hover">Take a closer look <ArrowUpRight size={18}/></div></div><div className="product-info"><span className="product-category">{product.category}</span><div><h3>{product.title}</h3><span>{formatPrice(product.price)}</span></div><p>{product.description}</p></div></motion.button>}
export default function Home(){
const reduced=useReducedMotion();
const [loading,setLoading]=useState(true),[scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false),[category,setCategory]=useState('All templates'),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<Product[]>([]),[cartOpen,setCartOpen]=useState(false),[faq,setFaq]=useState<number|null>(0),[notice,setNotice]=useState(''),[email,setEmail]=useState(''),[subscribed,setSubscribed]=useState(false),[info,setInfo]=useState<string|null>(null);
const [pricing,setPricing]=useState({currency:'INR',rate:1,approximate:false});
const analyticsBase=(process.env.NEXT_PUBLIC_ANALYTICS_API_URL||'').replace(/\/$/,'');
const formatPrice=(amount:number)=>new Intl.NumberFormat(undefined,{style:'currency',currency:pricing.currency,maximumFractionDigits:pricing.currency==='JPY'||pricing.currency==='KRW'?0:2}).format(amount*pricing.rate);
const trackClick=(product:Product)=>{if(!analyticsBase)return;void fetch(analyticsBase+'/api/clicks/'+product.slug,{method:'POST',keepalive:true}).catch(()=>{});};
const cursor=useRef<HTMLDivElement>(null), gallery=useRef<HTMLDivElement>(null), gallerySection=useRef<HTMLElement>(null);
useEffect(()=>{void fetch('/api/pricing').then(r=>r.ok?r.json() as Promise<{currency:string,rate:number,approximate:boolean}>:Promise.reject()).then(data=>{if(data.currency&&Number(data.rate)>0)setPricing(data)}).catch(()=>{});const t=setTimeout(()=>setLoading(false),900);try{const ids=JSON.parse(localStorage.getItem('forma-cart')||'[]');if(Array.isArray(ids))setCart([...products,bundle].filter(p=>ids.includes(p.id)))}catch{}return()=>clearTimeout(t)},[]);
useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(t)},[notice]);
useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();let lenis:Lenis|undefined;let raf=0;
if(!matchMedia('(prefers-reduced-motion:reduce)').matches){lenis=new Lenis({duration:1.1,anchors:true});const tick=(time:number)=>{lenis?.raf(time);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);lenis.on('scroll',ScrollTrigger.update);}
const handleScroll=()=>setScrolled(window.scrollY>500);window.addEventListener('scroll',handleScroll,{passive:true});
mm.add('(prefers-reduced-motion:no-preference)',()=>{gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.fromTo(el,{y:30,opacity:0},{y:0,opacity:1,duration:.8,scrollTrigger:{trigger:el,start:'top 91%',once:true}}));});
mm.add('(min-width:1100px) and (prefers-reduced-motion:no-preference)',()=>{const track=gallery.current,section=gallerySection.current;if(!track||!section)return;gsap.to(track,{x:()=>-Math.max(0,track.scrollWidth-section.clientWidth+140),ease:'none',scrollTrigger:{trigger:section,start:'top 110px',end:()=>'+='+Math.max(300,track.scrollWidth-section.clientWidth+140),scrub:1,pin:true,invalidateOnRefresh:true}})});
const pointer=(e:MouseEvent)=>{const el=cursor.current;if(!el)return;el.style.left=e.clientX+'px';el.style.top=e.clientY+'px';const target=(e.target as HTMLElement).closest<HTMLElement>('[data-cursor],button,a');el.textContent=target?.dataset.cursor||(target?'↗':'');el.classList.toggle('active',!!target);el.style.opacity='1';};
window.addEventListener('mousemove',pointer);return()=>{window.removeEventListener('mousemove',pointer);window.removeEventListener('scroll',handleScroll);cancelAnimationFrame(raf);lenis?.destroy();mm.revert()};
},[]);
const add=(p:Product)=>{const next=cart.some(x=>x.id===p.id)?cart:[...cart,p];setCart(next);try{localStorage.setItem('forma-cart',JSON.stringify(next.map(x=>x.id)))}catch{}setSelected(null);setCartOpen(true);setNotice('A little possibility, added to your bag.')};
const remove=(id:number)=>{const next=cart.filter(p=>p.id!==id);setCart(next);try{localStorage.setItem('forma-cart',JSON.stringify(next.map(x=>x.id)))}catch{}};
return <main>
<AnimatePresence>{loading&&<motion.div className="preloader" exit={{opacity:0}} transition={{duration:.25}} aria-hidden="true"><motion.span className="brand" initial={{y:12,opacity:0}} animate={{y:0,opacity:1}}>forma<motion.span animate={{rotate:180}} transition={{duration:1}}>✳</motion.span></motion.span><span>A little space for you.</span></motion.div>}</AnimatePresence>
<div ref={cursor} className="custom-cursor" aria-hidden="true"/>
<header className={scrolled?'nav-shell scrolled':'nav-shell'}><nav><a className="brand" href="#" aria-label="Forma home">forma<span>✳</span></a><div className="navlinks"><a href="#templates">The templates</a><a href="#why">Our philosophy</a><a href="#reviews">Kind words</a></div><div className="nav-actions"><button className="bag" onClick={()=>setCartOpen(true)} aria-label={`Open shopping bag, ${cart.length} items`}><ShoppingBag size={18}/>{cart.length>0&&<span>{cart.length}</span>}</button><Magnetic href="#templates" className="navcta">Find your flow <ArrowUpRight size={16}/></Magnetic><button className="menu-toggle" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>{menu&&<div className="mobile-menu">{[['The templates','#templates'],['Our philosophy','#why'],['Kind words','#reviews'],['The bundle','#bundle']].map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={16}/></a>)}</div>}</header>
<section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> A LITTLE STRUCTURE. A LOT OF POSSIBILITY.</div><h1 aria-label="Less chaos. More you.">{['Less','chaos.'].map((word,i)=><span className="word-mask" key={word}><motion.span initial={{y:reduced?0:120}} animate={{y:0}} transition={{delay:.8+i*.1,duration:.75,ease:[.22,1,.36,1]}}>{word}&nbsp;</motion.span></span>)}<br/>{['More','you.'].map((word,i)=><span className="word-mask" key={word}><motion.span initial={{y:reduced?0:120}} animate={{y:0}} transition={{delay:1+i*.1,duration:.75,ease:[.22,1,.36,1]}}>{i?<em>{word}</em>:word}&nbsp;</motion.span></span>)}<span className="headline-star">✳</span></h1><p>Thoughtfully crafted Notion templates to clear your mind,<br className="desktop"/> find your rhythm, and make room for what matters.</p><Magnetic href="#templates">Explore the templates <ArrowUpRight size={18}/></Magnetic><div className="hero-proof"><div className="avatars"><span>J</span><span>A</span><span>M</span><span>S</span></div><div><span className="stars">★★★★★</span><small>For beautifully busy minds, like yours.</small></div></div></div>
<div className="hero-art" onMouseMove={e=>{if(!reduced&&matchMedia('(pointer:fine)').matches){const r=e.currentTarget.getBoundingClientRect();gsap.to('.hero-workspace',{x:(e.clientX-r.left-r.width/2)*.025,y:(e.clientY-r.top-r.height/2)*.025,duration:.8});}}} onMouseLeave={()=>gsap.to('.hero-workspace',{x:0,y:0,duration:.8})}><div className="mesh"/><div className="hero-workspace"><Workspace/></div><div className="floating-note"><span>✦ &nbsp; A little daily progress</span><b>You’re in your<br/><em>getting-it-together era.</em></b><div>MON &nbsp; TUE &nbsp; WED &nbsp; THU &nbsp; FRI</div><div className="progress-dots">✓ &nbsp; ✓ &nbsp; ✓ &nbsp; ✓ &nbsp; ○</div></div><span className="art-caption">your fresh start, in one little click ↗</span><span className="notion-tag">N &nbsp; Made for Notion. Made for you.</span></div><div className="hero-bottom"><span>DESIGNED WITH INTENTION. BUILT FOR REAL LIFE.</span><a href="#featured">A little scroll, a fresh start ↓</a></div></section>
<section className="social-proof reveal"><div className="proof-intro">Small systems.<br/><em>Big little changes.</em><small>Illustrative community statistics</small></div><Counter value={5000} label="creative minds"/><Counter value={12000} label="fresh starts"/><div className="works-with"><span>AT HOME IN YOUR TOOLKIT</span><div><b>Ⓝ Notion</b><b>◈ Figma</b><b>☷ Slack</b></div><small>Independent templates. No affiliation.</small></div></section>
<section id="featured" ref={gallerySection} className="section featured"><div className="section-heading reveal"><div><div className="eyebrow">01 / THE FAVORITES</div><h2>A fresh start.<br/><em>In your own way.</em></h2></div><div className="heading-aside"><p>A few thoughtfully made spaces<br/>for whatever life looks like right now.</p><a href="#templates" className="text-link">Find your perfect fit <ArrowUpRight size={16}/></a></div></div><div className="gallery-viewport"><div ref={gallery} className="gallery-track">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p} onView={setSelected} formatPrice={formatPrice} onTrack={trackClick}/>)}</div></div><div className="gallery-foot"><span>MADE TO FIT YOUR LIFE. NOT THE OTHER WAY AROUND.</span><span>SCROLL TO EXPLORE <ArrowRight size={15}/></span></div></section>
<section id="templates" className="section catalog"><div className="section-heading reveal"><div><div className="eyebrow">02 / FIND YOUR FLOW</div><h2>There’s a space <em>for that.</em></h2></div><span className="catalog-count">{category==='All templates'?6:products.filter(p=>p.category===category).length} thoughtfully made templates</span></div><div className="filters" role="group" aria-label="Filter templates">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{category===c&&<motion.span className="filter-pill" layoutId="filter" transition={{type:'spring',bounce:.15,duration:.45}}/>}<span>{c}</span></button>)}</div><motion.div layout className="catalog-grid">{products.filter(p=>category==='All templates'||p.category===category).map(p=><ProductCard key={p.id} product={p} onView={setSelected} formatPrice={formatPrice} onTrack={trackClick}/>)}</motion.div><div className="trust-row"><span><Zap size={14}/> Instant access*</span><span><Headphones size={14}/> 30-day support*</span><span><Heart size={14}/> Yours to make your own</span></div><small className="demo-note">*Proposed launch offer. This is a demonstration storefront; no live purchases are being reported.</small></section>
<section id="why" className="section philosophy"><div className="philosophy-intro reveal"><span className="large-star">✳</span><div className="eyebrow">A LITTLE MORE INTENTION</div><h2>You don’t need to<br/>do more. Just make<br/><em>space for what matters.</em></h2><p>We believe a good system should feel like a deep breath.<br/>Not another thing on your to-do list.</p><Magnetic href="#templates">Meet your new favorite system <ArrowUpRight size={16}/></Magnetic></div><div className="benefits">{[[Layers,'Beautiful, but never just pretty.','Every detail has a purpose. Thoughtful layouts meet systems that actually make your day easier.'],[Zap,'Less setup. More living.','Skip the blank-page overwhelm. Duplicate, make it yours, and find your rhythm in minutes.'],[Heart,'Made for your kind of life.','Flexible by design. Keep what fits, change what doesn’t, and let your space grow with you.'],[Headphones,'A real human in your corner.','Helpful guides and a little encouragement. Getting organized shouldn’t mean figuring it all out alone.']].map(([Icon,title,text],i)=>{const I=Icon as typeof Heart;return <div className="benefit reveal" key={i}><div className={'benefit-icon icon-'+i}><I size={21} strokeWidth={1.5}/></div><div><h3>{String(title)}</h3><p>{String(text)}</p></div></div>})}</div></section>
<section id="reviews" className="testimonials"><div className="section-heading section reveal"><div><div className="eyebrow">KIND WORDS, HAPPY SPACES</div><h2>A little love <em>from the community.</em></h2><small>Sample testimonials for this concept. Replace with verified customer reviews before launch.</small></div><span className="review-rating">★★★★★<small>Less friction. More flow.</small></span></div><div className="marquee" tabIndex={0} aria-label="Sample customer testimonials; focus or hover to pause"><div className="marquee-track">{[...quotes,...quotes].map(([quote,name,role,initials],i)=><article className="quote" key={i} aria-hidden={i>=3}><span className="stars">★★★★★</span><blockquote>{quote}</blockquote><div><span className="quote-avatar">{initials}</span><span><b>{name}</b><small>{role}</small></span></div></article>)}</div></div></section>
<section id="bundle" className="section"><div className="bundle reveal"><div><div className="eyebrow">YOUR WHOLE LIFE. A LITTLE LIGHTER.</div><h2>Why pick one<br/>kind of <em>possibility?</em></h2><p>Meet the Everything Bundle. Six beautiful systems<br/>for your work, your life, and all the in-between.</p><div className="bundle-includes">{bundle.features.map(f=><span key={f}><Check size={15}/>{f}</span>)}</div></div><div className="bundle-price"><span className="bundle-badge">✦ THE MOST POPULAR WAY TO START</span><div className="price">{formatPrice(bundle.price)} <span>{pricing.approximate?'Approximate local display price':'Your local price'} · once, yours forever</span></div><p>A little investment in a lot more headspace.</p><Magnetic onClick={()=>add(bundle)}>Make room for everything <ArrowUpRight size={18}/></Magnetic><small>All six templates · One happy workspace</small></div></div></section>
<section id="faq" className="section faq-section"><div className="reveal"><div className="eyebrow">GOOD QUESTIONS</div><h2>A little clarity<br/><em>before you begin.</em></h2><p>Wondering about something?<br/>Let’s make it simple.</p></div><div className="faq-list">{questions.map(([q,a],i)=><div className="faq-item" key={q}><button aria-expanded={faq===i} aria-controls={'faq-'+i} onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<Minus size={17}/>:<Plus size={17}/>}</button><AnimatePresence initial={false}>{faq===i&&<motion.div id={'faq-'+i} initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:reduced?0:.3}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section>
<section className="section newsletter reveal"><span className="newsletter-star">✳</span><div className="eyebrow">A SMALL NOTE. A FRESH PERSPECTIVE.</div><h2>Good things, <em>in your inbox.</em></h2><p>Thoughtful tips, new templates, and a little nudge toward a calmer day.</p><form onSubmit={e=>{e.preventDefault();if(email.trim()){setSubscribed(true);}}}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" required placeholder="Your email, please" value={email} onChange={e=>{setEmail(e.target.value);setSubscribed(false)}}/><button type="submit" aria-label="Sign up for the newsletter"><ArrowUpRight size={22}/></button></form><small role="status">{subscribed?'Preview complete — your address has not been sent or subscribed. Connect your email provider to go live.':'Just the good stuff. No noise. Demo signup — no data is sent.'}</small></section>
<footer><div className="footer-top"><div><a className="brand" href="#">forma<span>✳</span></a><p>A little structure.<br/>A lot more you.</p></div><div><b>FIND YOUR SPACE</b>{categories.slice(1).map(c=><a key={c} href="#templates" onClick={()=>setCategory(c)}>{c}</a>)}</div><div><b>GOOD TO KNOW</b><a href="#why">Our philosophy</a><a href="#faq">Questions & answers</a><a href="#bundle">The Everything Bundle</a><button onClick={()=>setInfo('Support')}>Get in touch <ArrowUpRight size={12}/></button></div><div><b>LET’S STAY CLOSE</b><button onClick={()=>setInfo('Instagram')}>Instagram <Instagram size={13}/></button><button onClick={()=>setInfo('Pinterest')}>Pinterest <ArrowUpRight size={13}/></button><a href="#newsletter-email">A little newsletter <Mail size={13}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Forma. Made with a little intention.</span><div><button onClick={()=>setInfo('Privacy')}>Privacy</button><button onClick={()=>setInfo('Terms')}>Terms</button><span className="payment-label">VISA &nbsp; ◉◉ &nbsp; PayPal</span></div></div><p className="demo-note">Concept storefront · Sample products, prices, statistics, and reviews · Razorpay payment page connected · Itemized verification pending</p></footer>
<Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="product-dialog" data-lenis-prevent>{selected&&<><div className={'dialog-preview '+selected.color}><Workspace title={selected.title}/></div><span className="product-category">{selected.category} / NOTION TEMPLATE</span><DialogTitle className="dialog-title">{selected.title}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><ul className="dialog-features">{selected.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Magnetic onClick={()=>add(selected)}>Add to bag — {formatPrice(selected.price)} <ShoppingBag size={17}/></Magnetic><small>Demo product preview · Notion duplication link supplied at launch</small></>}</DialogContent></Dialog>
<Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="cart-dialog" data-lenis-prevent><DialogTitle className="dialog-title">Your little fresh start.</DialogTitle><DialogDescription>{cart.length?'A few good things, ready when you are.':'Your bag is waiting for a little possibility.'}</DialogDescription>{cart.length?<><div className="cart-items">{cart.map(p=><div className="cart-item" key={p.id}><span className={'cart-symbol '+p.color}>✳</span><div><b>{p.title}</b><small>Notion template · Digital product</small></div><span>{formatPrice(p.price)}</span><button aria-label={'Remove '+p.title} onClick={()=>remove(p.id)}><Trash2 size={16}/></button></div>)}</div><div className="cart-total"><span>Total · {pricing.currency}</span><b>{formatPrice(cart.reduce((sum,p)=>sum+p.price,0))}</b></div><button className="button" onClick={()=>{cart.forEach(trackClick);window.open('https://razorpay.me/@keshavchhabra','_blank','noopener,noreferrer');setNotice('Razorpay opened securely. Automated payment verification and delivery will be enabled after the Razorpay keys and webhook are connected.')}}>Pay securely with Razorpay <ArrowRight size={17}/></button><p className="demo-note">Displayed local prices are estimates. Until itemized Razorpay checkout is connected, confirm the final ₹ amount on Razorpay before paying.</p></>:<button className="button" onClick={()=>{setCartOpen(false);document.getElementById('templates')?.scrollIntoView({behavior:reduced?'instant':'smooth'})}}>Explore the templates <ArrowUpRight size={16}/></button>}</DialogContent></Dialog>
<Dialog open={!!info} onOpenChange={open=>{if(!open)setInfo(null)}}><DialogContent><DialogTitle className="dialog-title">{info}</DialogTitle><DialogDescription>{info==='Privacy'?'This demo stores your shopping bag only in your browser. Newsletter input is not transmitted. External fonts and preview imagery are loaded from Google Fonts and Unsplash. Add your full privacy policy before collecting customer data.':info==='Terms'?'This is a concept storefront. Products and prices are illustrative, no payments are accepted, and no purchase contract is created. Publish your license, refund policy, and business terms before launch.':info==='Support'?'A real support address has not been added yet. Connect your business email before launching this storefront.':'The Forma '+info+' account has not been linked yet. Add your real profile URL before launch.'}</DialogDescription></DialogContent></Dialog>
<AnimatePresence>{notice&&<motion.div role="status" className="toast" initial={{y:25,opacity:0}} animate={{y:0,opacity:1}} exit={{opacity:0}}>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={16}/></button></motion.div>}</AnimatePresence>
</main>}
